# Generated by Django 5.2.6 on 2025-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
